[package]
name = "not-wallpaper-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
wayland-client = "0.31"
wayland-protocols-wlr = { version = "0.2", features = ["client"] }
smithay-client-toolkit = "0.19"
anyhow = "1"
memmap2 = "0.9"
tempfile = "3"
crossbeam-channel = "0.5"
md5 = "0.7"
dirs = "5.0"
